#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     COMPASS,        sensorVirtualCompass)
#pragma config(Sensor, S3,     LIGHT,          sensorLightActive)
#pragma config(Sensor, S4,     ULTRA,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_FR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_FL,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_BR,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_BL,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     LIFT_R,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LIFT_L,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "FTC_Definitions.c"
#define   PRACTICE // If not defined, then competition mode
#include "FTC_Declarations.c"
#include "FTC_OtherFunctions.c"
#include "FTC_Initialize.c"
#include "FTC_InputAndOutput.c"
#include "FTC_Autonomous.c"

/*
By Joseph Dykstra
For the CS2N FTC Ring It Up! Challenge
2013-06-27 - 2013-0?-??

Instructions:
Robot:	Gyro ScissorBot
Mode:	CS2N Mode
Start:	Start Point 1

Do not move the robot at all from it's starting position.
*/

task main()
	{
	initialize(N_EAST); //Which way does the robot start pointing?
	autoReset(START);
	//	TYPE,	Left,	Right,	Other,	End Type,	Delay
	auto(CMP_2,	RHT_45,	FULL,	LOW_SH,	DRIV_READY,	PID);	//Turn toward S dispenser
	auto(STR,	EAST,	11300,	LOW_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	LFT_90,	FULL,	LOW_SH,	DRIV_READY,	PID);	//Turn to SE hooks
	auto(STR,	NORTH,	9150,	HIG_SH,	DRIV_READY,	NEXT);	//Forward - High
	auto(STR,	NORTH,	-7200,	HIG_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	NORTH,	7200,	MED_SH,	DRIV_READY,	NEXT);	//Forward - Med
	auto(STR,	NORTH,	-7200,	MED_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	NORTH,	7150,	LOW_SH,	DRIV_READY,	NEXT);	//Forward - Low
	auto(STR,	NORTH,	-7200,	LOW_OP,	DRIV_READY,	NEXT);	//Backward

	auto(CMP_2,	RHT_90,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn toward corner hook
	auto(STR,	EAST,	8100,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn into corner hook
	auto(STR,	S_EAST,	1600,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	-1350,	FULL,	CRN_OP,	DRIV_READY,	PID);	//Turn toward E dispenser

	auto(STR,	NORTH,	10400,	DRP_SH,	DRIV_READY,	NEXT);	//Forward - E dispenser to 4 tiles
	auto(CMP_2,	-250,	FULL,	DRP_OP,	DRIV_READY,	PID);	//Turn
	auto(STR,	650,	8000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	N Tile
	auto(STR,	650,	-4000,	DRP_SH,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	650,	-4000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	-200,	FULL,	DRP_OP,	DRIV_READY,	PID);	//Turn
	auto(STR,	N_WEST,	8300,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	W Tile
	auto(STR,	N_WEST,	-3300,	DRP_SH,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	1350,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn - Straight back
	auto(STR,	EAST,	-2200,	DRP_SH,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	RHT_45,	FULL,	DRP_OP,	DRIV_READY,	PID);	//Turn - 45 curve
	auto(STR,	S_EAST,	-6620,	DRP_SH,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	RHT_45,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn - Align

	auto(STR,	SOUTH,	-2420,	LOW_LV,	DRIV_READY,	NEXT);	//Backward - N dispenser to NW hooks
	auto(STR,	SOUTH,	7900,	HIG_SH,	DRIV_READY,	NEXT);	//Forward - High
	auto(STR,	SOUTH,	-7800,	HIG_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	SOUTH,	7400,	MED_SH,	DRIV_READY,	NEXT);	//Forward - Med
	auto(STR,	SOUTH,	-7600,	MED_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	SOUTH,	7500,	LOW_SH,	DRIV_READY,	NEXT);	//Forward - Low
	auto(STR,	SOUTH,	-7500,	LOW_OP,	DRIV_READY,	NEXT);	//Backward

	auto(CMP_2,	RHT_90,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn toward corner hook
	auto(STR,	3600,	8850,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn into corner hook
	auto(STR,	4050,	1000,	CRN_SH,	DRIV_READY,	NEXT);	//Let go
	auto(CMP_2,	-1350,	FULL,	CRN_OP,	DRIV_READY,	NEXT);	//Turn toward W dispenser

	auto(STR,	SOUTH,	10400,	DRP_SH,	DRIV_READY,	NEXT);	//Forward - E dispenser to 4 tiles
	auto(CMP_2,	-250,	FULL,	DRP_OP,	DRIV_READY,	NEXT);	//Turn
	auto(STR,	2450,	8000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	N Tile
	auto(STR,	2450,	-4000,	DRP_SH,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	2450,	-4000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	250,	FULL,	DRP_SH,	DRIV_READY,	NEXT);	//Turn
	auto(STR,	SOUTH,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	E Tile
	auto(STR,	SOUTH,	-4000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_SH,	DRIV_READY,	NEXT);	//Turn
	auto(STR,	S_EAST,	8300,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	W Tile
	auto(STR,	S_EAST,	-8300,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	S_EAST,	2200,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	S Tile
	auto(STR,	S_EAST,	-200,	DRP_OP,	DRIV_READY,	NEXT);	//Backward

	autoReset(FINISH);
	while(1==1)
		{zeroMotors();
		output();
		wait1Msec(10);}
	}

/* BUGS...
LIFT_READY was not working correctly, triggered too soon; maybe working now.

too far toward 2nd corner

*/



/* KEEP CODE

	auto(CMP_2,	1350,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Turn to get around pole - N side to S side, backward
	auto(STR,	S_EAST,	-5000,	LOW_LV,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	RHT_90,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Turn to get around pole
	auto(STR,	S_WEST,	-2300,	LOW_LV,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Align with S wall

	auto(CMP_2,	RHT_90,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn toward corner hook - N Dispenser to NW pole
	auto(STR,	3600,	9500,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn into corner hook
	auto(CMP_2,	-1350,	FULL,	LOW_OP,	DRIV_READY,	PID);	//Turn away from corner hook



	auto(STR,	2450,	9000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	^
	auto(STR,	2450,	-9000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	250,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	SOUTH,	4000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	>
	auto(STR,	SOUTH,	-5000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	S_EAST,	8500,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	<
	auto(STR,	S_EAST,	-8500,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	S_EAST,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	v
	auto(STR,	S_EAST,	-3000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_OP,	DRIV_READY,	PID);	//Turn toward E dispenser



	auto(STR,	EAST,	10000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward across field
	auto(STR,	EAST,	10000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward across field
	auto(CMP_2,	-1150,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	650,	7000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	^
	auto(STR,	650,	-7000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	250,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	NORTH,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	>
	auto(STR,	NORTH,	-5000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	N_WEST,	7000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	<
	auto(STR,	N_WEST,	-7000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	N_WEST,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	v
	auto(STR,	N_WEST,	-3000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward

*/
