#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  none)
#pragma config(Sensor, S2,     COMPASS,        sensorVirtualCompass)
#pragma config(Sensor, S3,     LIGHT,          sensorLightActive)
#pragma config(Sensor, S4,     ULTRA,          sensorSONAR)
#pragma config(Motor,  mtr_S1_C1_1,     DRIVE_FR,      tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     DRIVE_FL,      tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     DRIVE_BR,      tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     DRIVE_BL,      tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     LIFT_R,        tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     LIFT_L,        tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define   PRACTICE // If not defined, then competition mode
#include "Definitions.c"
#include "Declarations.c"
#include "OtherFunctions.c"
#include "Initialize.c"
#include "InputAndOutput.c"
#include "Autonomous.c"

/*
By Joseph Dykstra
For the CS2N FTC Ring It Up! Challenge
2013-06-27 - 2013-0?-??

Use Gyro ScissorBot, and do not move it at all from it's starting position.
*/

task main()
	{
	initialize(N_EAST); //Which way does the robot start pointing?
	autoReset(0); // 0 = Start, 1 = Finish
	//	TYPE,	Left,	Right,	Other,	End Type,	Delay
	auto(CMP_2,	RHT_45,	FULL,	LOW_SH,	DRIV_READY,	PID);	//Turn toward S dispenser
	auto(STR,	EAST,	11300,	LOW_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	LFT_90,	FULL,	LOW_SH,	DRIV_READY,	PID);	//Turn to hooks
	auto(STR,	NORTH,	9150,	HIG_SH,	DRIV_READY,	NEXT);	//Forward - High
	auto(STR,	NORTH,	-7200,	HIG_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	NORTH,	7200,	MED_SH,	DRIV_READY,	NEXT);	//Forward - Med
	auto(STR,	NORTH,	-7200,	MED_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	NORTH,	7150,	LOW_SH,	DRIV_READY,	NEXT);	//Forward - Low
	auto(STR,	NORTH,	-1000,	LOW_OP,	DRIV_READY,	NEXT);	//Backward

	auto(CMP_2,	1350,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Turn to get around pole
	auto(STR,	S_EAST,	-5000,	LOW_LV,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	RHT_90,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Turn to get around pole
	auto(STR,	S_WEST,	-2300,	LOW_LV,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	LOW_LV,	DRIV_READY,	PID);	//Align with S wall

	auto(STR,	SOUTH,	-7300,	LOW_LV,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	SOUTH,	7400,	HIG_SH,	DRIV_READY,	NEXT);	//Forward - High
	auto(STR,	SOUTH,	-7500,	HIG_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	SOUTH,	7100,	MED_SH,	DRIV_READY,	NEXT);	//Forward - Med
	auto(STR,	SOUTH,	-7300,	MED_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	SOUTH,	7200,	LOW_SH,	DRIV_READY,	NEXT);	//Forward - Low
	auto(STR,	SOUTH,	-7900,	LOW_OP,	DRIV_READY,	NEXT);	//Backward

	auto(CMP_2,	RHT_90,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn toward corner hook
	auto(STR,	3600,	9500,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn into corner hook
	auto(CMP_2,	-1350,	FULL,	LOW_OP,	DRIV_READY,	PID);	//Turn away from corner hook

	auto(STR,	SOUTH,	9800,	DRP_OP,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	-250,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	2450,	9000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	^
	auto(STR,	2450,	-9000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	250,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	SOUTH,	4000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	>
	auto(STR,	SOUTH,	-5000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	S_EAST,	8500,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	<
	auto(STR,	S_EAST,	-8500,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	S_EAST,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	v
	auto(STR,	S_EAST,	-3000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_OP,	DRIV_READY,	PID);	//Turn toward E dispenser

	auto(STR,	EAST,	10000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward across field
	auto(STR,	EAST,	10000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward across field
	auto(CMP_2,	-1150,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	650,	7000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	^
	auto(STR,	650,	-7000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	250,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	NORTH,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	>
	auto(STR,	NORTH,	-5000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(CMP_2,	LFT_45,	FULL,	DRP_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	N_WEST,	7000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	<
	auto(STR,	N_WEST,	-7000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward
	auto(STR,	N_WEST,	3000,	DRP_SH,	DRIV_READY,	NEXT);	//Forward -	v
	auto(STR,	N_WEST,	-3000,	DRP_OP,	DRIV_READY,	NEXT);	//Backward

	auto(CMP_2,	RHT_90,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn
	auto(STR,	N_EAST,	-12800,	CRN_SH,	DRIV_READY,	NEXT);	//Backward to last dispenser
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn toward corner hook
	auto(STR,	EAST,	9200,	CRN_SH,	DRIV_READY,	NEXT);	//Forward
	auto(CMP_2,	RHT_45,	FULL,	CRN_SH,	DRIV_READY,	PID);	//Turn into corner hook
	auto(STR,	S_EAST,	-850,	CRN_OP,	DRIV_READY,	300);	//Let go

	autoReset(1);
	while(1==1)
		{zeroMotors();
		output();}
	}

/* BUGS...

LIFT_READY was not working correctly, triggered too soon; maybe working now.

1st corner is sloppy
1st left and down
2nd pole, top hook; missed the ring at dispenser

*/
